---
- name: Create elastalert directory
  file:
    path: /opt/{{ ea_dir }}
    state: directory
    mode: 0755
  become: true

- name: Clone elastalert
  git:
    repo: "{{ ea_git }}"
    dest: /opt/{{ ea_dir }}
    version: master
  become: true

- name: Clone rules
  git:
    repo: "{{ rules_git }}"
    dest: /opt/{{ ea_dir }}/rules
    version: master
  become: true

- name: Copy config
  template:
    src: 'config.yaml.tpl'
    dest: '/opt/{{ ea_dir }}/config.yaml'
    mode: 0600
  become: true

- name: Copy elasticsearch config
  template:
    src: 'elasticsearch.yml.tpl'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    mode: 0600
  become: true
