---
  - name: Create elastalert directory
    file:
      path: /opt/{{ ea_dir }}
      state: directory
      mode: 0755
    become: yes

  - name: Clone elastalert
    git:
      repo: "{{ ea_git }}"
      dest: /opt/{{ ea_dir }}
    tags: skip_ansible_lint
    become: yes

  - name: Clone rules
    git:
      repo: "{{ rules_git }}"
      dest: /opt/{{ ea_dir }}/rules
    tags: skip_ansible_lint
    become: yes

  - name: Copy config
    template: src=config.yaml dest=/opt/{{ ea_dir }}
    become: yes

  - name: Copy elasticsearch config
    template: src=elasticsearch.yml dest=/etc/elasticsearch
    become: yes
