---
- name: Create elastalert directory
  file:
    path: /opt/{{ ea_dir }}
    state: directory
    mode: 0755
  become: true

- name: Clone elastalert
  git:
    repo: "{{ ea_git }}"
    dest: /opt/{{ ea_dir }}
  tags: skip_ansible_lint
  become: true

- name: Clone rules
  git:
    repo: "{{ rules_git }}"
    dest: /opt/{{ ea_dir }}/rules
  tags: skip_ansible_lint
  become: true

- name: Copy config
  template: src=config.yaml.tpl dest=/opt/{{ ea_dir }}/config.yaml
  become: true

- name: Copy elasticsearch config
  template: src=elasticsearch.yml.tpl dest=/etc/elasticsearch/elasticsearch.yml
  become: true
