---
  - name: Install elastalert
    pip:
      name: elastalert
    become: yes

  - name: Install pexpect
    pip:
      name: pexpect
    become: yes

  - name: Install elasticsearch
    pip:
      name: elasticsearch
    become: yes

  - name: Install requirements
    pip:
      requirements: /opt/{{ ea_dir }}/requirements.txt

  - name: Create index
    command: elastalert-create-index --host localhost --port 9200 --no-ssl --index elastalert --config /opt/{{ ea_dir }}/config.yaml
    tags: skip_ansible_lint

  - name: Copy supervisor config
    template:
      src: elastalert.conf
      dest: /etc/supervisor/con.f/elastalert.conf
    become: yes

  - name: Update supervisor
    command: supervisorctl update
    become: yes

  - name: Restart supervisor
    command: supervisorctl restart all
    become: yes