---
  - name: Install elastalert
    pip:
      name: elastalert
    become: yes

  - name: Install requirements
    pip:
      requirements: /opt/{{ ea_dir }}/requirements.txt
    become: yes

  - name: Create index
    command: elastalert-create-index --host localhost --port 9200 --no-ssl --index elastalert --config /opt/{{ ea_dir }}/config.yaml
    become: yes