---
  - name: Install elastalert
    pip:
      name: elastalert
    become: yes

  - name: Install requirements
    pip:
      requirements: /opt/{{ ea_dir }}/requirements.txt
    become: yes

  - name: Wait for Elasticsearch to become ready
    uri:
      url: "{{ logstash_elasticsearch_hosts }}"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 15
    delay: 10

  - name: Create index
    command: elastalert-create-index --host localhost --port 9200 --no-ssl --index elastalert --config /opt/{{ ea_dir }}/config.yaml
    become: yes
    tags: skip_ansible_lint
